swagger: '2.0'
info:
  title: Test API
  description: Stub API, with the sole purpose of presenting swagger code generation.
  version: "0.0.1"
host: com.rivancic.swagger
schemes:
  - https
basePath: /v1
produces:
  - application/json
parameters:
  Path:
    name: path
    in: path
    description: required "path" path parameter
    required: true
    type: string
  Query:
    name: query
    description: optional "query" query parameter
    in: query
    required: false
    type: string
  Header:
    name: X-Rivancic-Header
    in: header
    description: Optional custom header
    required: false
    type: string
paths:
  /test:
    get:
      summary: Returns test response
      description: |
        Test method. It will always return test response.
      parameters:
        - $ref: '#/parameters/Path'
        - $ref: '#/parameters/Query'
        - $ref: '#/parameters/Header'
      tags:
        - swagger-api
      responses:
        200:
          description: Test response
          schema:
            $ref: '#/definitions/TestResponse'
          examples:
            application/json:
              response: "Test OK"
definitions:
  TestResponse:
    type: object
    properties:
      response:
        type: string
        description: Text value "Test OK" of the test response.
